name: Render Resume

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run it manually

jobs:
  rendercv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rendercv/rendercv-pipeline-action@v0
        with:
          resume_yaml_file: resume.yaml
          # This will automatically create a release with the PDF